<script src="{{ asset('dashboard/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/dataTables.buttons.min.js') }}"></script>
{{-- <script src="{{ asset('dashboard/plugins/datatables/buttons.bootstrap4.min.js') }}"></script> --}}
<script src="{{ asset('dashboard/plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('dashboard//plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('dashboard/plugins/datatables/responsive.bootstrap4.min.js') }}"></script>
